services:
  db:
    image: postgres:15
    container_name: bodyfuel_db
    environment:
      POSTGRES_USER: bodyfuel
      POSTGRES_PASSWORD: bodyfuel
      POSTGRES_DB: bodyfuel
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: bodyfuel_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: bodyfuel_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      EDAMAM_APP_ID: cea4c385
      EDAMAM_APP_KEY: de2b210d707f9956a9126c66d18d05c3

  frontend:
    build: ./frontend
    container_name: bodyfuel_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  scraper:
    build: ./scraper
    container_name: bodyfuel_scraper
    depends_on:
      - db
    environment:
      VITONICA_URLS: https://www.vitonica.com/categoria/recetas-saludables/record/20,https://www.vitonica.com/categoria/recetas-saludables/record/40,https://www.vitonica.com/categoria/recetas-saludables/record/60,https://www.vitonica.com/categoria/recetas-saludables/record/80,https://www.vitonica.com/categoria/recetas-saludables/record/100